name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  cloud_firestore: ^5.0.0
  timeago: ^3.6.1

  flutter_local_notifications: ^17.1.2


dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true