name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.2

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
 
  dart_firebase_admin: ^0.3.1
  dotenv: ^4.2.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
